### ISSUE TITLE
Elasticsearch Password is stored in flows.json, not encrypted in flow_creds.json

### ISSUE THREAD

**Issue by NickBorgers** [objt-ev/node-red-contrib-log-elk#1]
** Describe issue **
This node stores the Elasticsearch password in a way that causes it to be written to `flows.json` instead of `flows_creds.json`. This is definitely [exposing peoples' credentials, like mine right here](https://github.com/NickBorgers/node-red/blob/79a8a80421b1d5753c47e1ad2d4608c64df2602b/flows.json#L166) because [I'm using the Projects feature to back up my flows to GitHub](https://nodered.org/docs/user-guide/projects/).

** Your flow here **
<removed link to line with password b/c the commit contains a credential that is harder to rotate>

[I found this documentation in the Node Red project which seems to be describing how to store configuration in the credential type](https://nodered.org/docs/creating-nodes/credentials), but I'm unfamiliar with writing my own nodes.

[X-Link to this issue I raised for the same problem on a different node's project](https://github.com/andreypopov/node-red-contrib-miio-roborock/issues/54)
[X-Link 2](https://github.com/NRCHKB/node-red-contrib-homekit-bridged/issues/507)

**Comment by objt-ev** [comment]
which version are you using?

**Comment by NickBorgers** [comment]
`1.2.3`
https://github.com/NickBorgers/node-red/blob/add-automated-rendering/.automated-rendering/node-red/package.json#L10
<img width="590" alt="Screenshot 2022-11-27 at 11 24 36 AM" src="https://user-images.githubusercontent.com/1139580/204146388-1e1db28d-cad8-4cd8-89de-4c20bad7733b.png">

[I do see why you're asking... looks like you used the `credential` feature](https://github.com/objt-ev/node-red-contrib-log-elk/blob/f406569dd288e0393afc748750ae2571d689cd8e/log-elk-logger.html#L4-L7)

I'm going to try deleting the elasticsearch configuration and recreating it.

**Comment by NickBorgers** [comment]
Huh, so I think the way I titled the issue is inaccurate, as my `flows_cred.json` was indeed modified suggesting that the password is stored there also...
https://github.com/NickBorgers/node-red/commit/cd40495df6a879c90fb9fd31f23f01da06536e43

**Comment by NickBorgers** [comment]
I'm totally ignorant about how these bits fit together, but some observations:

- [The username and password are defined as `defaults`](https://github.com/objt-ev/node-red-contrib-log-elk/blob/f406569dd288e0393afc748750ae2571d689cd8e/log-elk-logger.html#L11-L12); maybe this causes them to be duplicated into the `flows.json`
- The credentials are registered twice, [one here](https://github.com/objt-ev/node-red-contrib-log-elk/blob/f406569dd288e0393afc748750ae2571d689cd8e/log-elk-logger.html#L4-L7) and [again here](https://github.com/objt-ev/node-red-contrib-log-elk/blob/f406569dd288e0393afc748750ae2571d689cd8e/log-elk-logger.js#L123-L129)

**Comment by NickBorgers** [comment]
Yeah it's the `defaults`, that's real silly on Node Red's part: https://github.com/objt-ev/node-red-contrib-log-elk/blob/f406569dd288e0393afc748750ae2571d689cd8e/log-elk-logger.html#L11-L12

I tested this by:

1. Pull my [node-red repo and checkout the branch](https://github.com/NickBorgers/node-red/tree/add-automated-rendering) I'm working on to generate screenshots of my flows and possibly implement CI
1. Launch a container using my flows by running `make` (GNU Make)
1. In another terminal, modify your code by removing the `defaults` for `username` and `password`: `docker exec -it node-red nano node_modules/node-red-contrib-log-elk/log-elk-logger.html`
1. Ctrl+C the first terminal where you ran `make` and then run `docker start node-red` to restart Node Red with the change
1. Interact with the node-red at `http://127.0.0.1:8080` to delete the Elasticsearch config (on the Log page) and recreate it
1. Look at `flows.json` by running: `docker exec -it node-red nano /data/flows.json` and see that the `username` and `password` are no longer present (I ran Ctrl+W then searched for `elastic`)

**Comment by NickBorgers** [comment]
I've reported this to Node Red based on [their security policy](https://github.com/node-red/node-red/security/policy).

I believe there is still a fix to be made here of deleting these two-lines and releasing a minor version bump:
https://github.com/objt-ev/node-red-contrib-log-elk/blob/f406569dd288e0393afc748750ae2571d689cd8e/log-elk-logger.html#L11-L12

[I've offered a PR, but don't know your release mechanics for this repo.](https://github.com/objt-ev/node-red-contrib-log-elk/pull/2)

**Comment by objt-ev** [comment]
Hi Nick,

thanks for sorting this all out.
I have just released v1.2.4 with your PR in it.

kind regards,
Erwin


-------- Oorspronkelijk bericht --------
Van: Nick Borgers ***@***.***>
Datum: 27/11/2022 18:09 (GMT+01:00)
Aan: objt-ev/node-red-contrib-log-elk ***@***.***>
Cc: Erwin Vervondel ***@***.***>, Comment ***@***.***>
Onderwerp: [EXTERNAL] Re: [objt-ev/node-red-contrib-log-elk] Elasticsearch Password is stored in flows.json, not encrypted in flow_creds.json (Issue #1)


EXTERNAL
________________________________


I've reported this to Node Red based on their security policy<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnode-red%2Fnode-red%2Fsecurity%2Fpolicy&data=05%7C01%7Cerwin.vervondel%40aptean.com%7C1ddde4f3929949d2a04808dad09a3099%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C638051657903999422%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qO2Dpe3RixOwvhy2QG7iCMU2n5%2BM7DDfjIimPxrpEXA%3D&reserved=0>.

I believe here is still a fix to be made here of deleting these two-lines and releasing a minor version bump:
https://github.com/objt-ev/node-red-contrib-log-elk/blob/f406569dd288e0393afc748750ae2571d689cd8e/log-elk-logger.html#L11-L12<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fobjt-ev%2Fnode-red-contrib-log-elk%2Fblob%2Ff406569dd288e0393afc748750ae2571d689cd8e%2Flog-elk-logger.html%23L11-L12&data=05%7C01%7Cerwin.vervondel%40aptean.com%7C1ddde4f3929949d2a04808dad09a3099%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C638051657903999422%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=POE5b%2FTkEi6pX3pE4llc8vn07n8mgR%2BV0jcs%2FGy%2F9SI%3D&reserved=0>

I've offered a PR, but don't know your release mechanics for this repo.<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fobjt-ev%2Fnode-red-contrib-log-elk%2Fpull%2F2&data=05%7C01%7Cerwin.vervondel%40aptean.com%7C1ddde4f3929949d2a04808dad09a3099%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C638051657903999422%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kGjeG0tmeWnsrC%2FRgZsYEq3JCa9OIi57Yo%2BvODuj610%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fobjt-ev%2Fnode-red-contrib-log-elk%2Fissues%2F1%23issuecomment-1328296765&data=05%7C01%7Cerwin.vervondel%40aptean.com%7C1ddde4f3929949d2a04808dad09a3099%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C638051657903999422%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VXPbwX6Dz9t3q54n2es87io4SyJ%2ByywqX97XR8fsM7o%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMQEAWWKZUVKI366XXF72SLWKOIVZANCNFSM6AAAAAASMJNRRE&data=05%7C01%7Cerwin.vervondel%40aptean.com%7C1ddde4f3929949d2a04808dad09a3099%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C638051657903999422%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gHF9%2FxbEmz8216vF6hE42ps%2F3RoehF0RrDL9%2FnJL%2Br0%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

This message contains information that is confidential and/or may be privileged. If you are not the intended recipient, you are hereby notified that any use, dissemination, distribution or copy of this message and/or its attachments is strictly prohibited. If you have received this message in error, please advise the sender immediately by replying to this email and delete this message. We are committed to your privacy. For more information, please see our Privacy Policy at https://www.aptean.com/privacy-statement
